<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_File Uploader_drag-drop-upload</name>
   <tag></tag>
   <elementGuidId>8cb801f6-bdbb-43a8-97d1-4b468b82ef6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drag-drop-upload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#drag-drop-upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ecf6e652-3063-4d73-b9fc-6d287a2e0d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dz-success-mark dz-clickable</value>
      <webElementGuid>778edde7-c434-4867-9674-e9cf540ead38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-drop-upload</value>
      <webElementGuid>d11282c3-1d41-403d-9b36-8b8b072c30dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-drop-upload&quot;)</value>
      <webElementGuid>769656e5-6fbf-41fd-b310-8b8384262bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='drag-drop-upload']</value>
      <webElementGuid>5f45dff4-0a8b-4695-bc1f-804d3b36811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]</value>
      <webElementGuid>c2a9ccc7-2667-4abf-84b0-3835d6d21a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploader'])[1]/following::div[1]</value>
      <webElementGuid>c3b18b68-e23d-4752-b3bc-d5bb09a85a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔'])[1]/preceding::div[3]</value>
      <webElementGuid>d76b8a7a-dd4d-425a-a978-17b4ab50fd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>834a3e6b-7c61-4107-b9c2-46e364bdb141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'drag-drop-upload']</value>
      <webElementGuid>047d5ae3-c32c-4d73-8ede-373beaac34b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
